### ISSUE TITLE
Conda-forge channel installation for Windows

### ISSUE THREAD

**Issue by akbaritabar** [vtraag/leidenalg#32]
Dear Vincent,

First, thanks for Leidenalg.
This might be more of a "feature-request", I am not sure.

I use a yml file (like below) to make conda environments from conda-forge that works fine on Linux and Mac. But on Windows it doesn't work as leidenalg exists only on your channel (https://anaconda.org/vtraag/leidenalg) and on conda-forge (https://anaconda.org/conda-forge/leidenalg) only for Mac and Linux.

```yaml
name: testenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.*
  - numpy
  - pandas
  - dask
  - pyarrow
  - jupyterlab
  - matplotlib
  - networkx
  - scipy
  - seaborn
  - scikit-learn
  - statsmodels
  - beautifulsoup4
  - requests
  - python-graphviz
  - python-igraph
  - leidenalg

```

When I remove leidenalg from above list, install the environment, activate it and install leidenalg from your channel, it takes for ever and for few times gives "Solving environment: failed with initial frozen solve. Retrying with flexible solve" (https://github.com/conda/conda/issues/9367).

My workaround is to remove igraph from yaml above, after environment is setup, install both igraph and leidenalg from your channel on conda-forge. But, doing this downgrades my python from 3.8 to 3.7.6 and igraph from 0.8 to 0.7 and some other libraries (unfortunately anaconda prompt is not scrolling up enough to print the list here, but it was around 15-20 libraries).

Now, I don't know if my way is the best way to install on Windows. Since with yml file it takes care of contradictions and requirements (I have been told so)

What would be your suggestion on how to install on Windows?
Thanks.
